import type { Metadata } from "next";

import {geistSans, geistMono, cormorant, robotoRegular, robotoBold, BitcountPropDouble, oswaldLight, oswaldRegular } from "./fonts";
import "./globals.css";
import { Header } from "@/components/header/Header";
import { Cart } from "@/components/cart/Cart";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} 
          ${geistMono.variable} 
          ${cormorant.variable} 
          ${BitcountPropDouble.variable} 
          ${robotoRegular.variable} 
          ${robotoBold.variable} 
          ${oswaldLight.variable} 
          ${oswaldRegular.variable} 
          antialiased`}
      >
        <>
          <Header />
          <Cart />
          {children}
        </>
      </body>
    </html>
  );
}
